### PR TITLE
Fix for the valid_range attribute definition in GNSSRO converters

### LINKED ISSUE #779: [Bug] Issue with valid_range definition when using the netCDF4 python package
## Current behavior (describe the bug)
The netCDF4 python library is complaining when reading the variables with `valid_range` attribute saved. An example of the error message can be seen below:

```
  File "src/netCDF4/_netCDF4.pyx", line 4445, in netCDF4._netCDF4.Variable.__getitem__
  File "src/netCDF4/_netCDF4.pyx", line 4604, in netCDF4._netCDF4.Variable._toma
  File "src/netCDF4/_netCDF4.pyx", line 4801, in netCDF4._netCDF4.Variable._check_safecast
ValueError: could not convert string to float: '0 - 500 N'
```

Currently, that attribute is being saved like:

```
group: ObsValue {
  variables:
  	float bending_angle(nlocs) ;
  		string bending_angle:valid_range = "-0.001 - 0.08 Radians" ;
````

but I believe that the package is expecting a list with two elements, for example:

```
group: ObsValue {
  variables:
  	float bending_angle(nlocs) ;
  		string bending_angle:valid_range = -0.001, 0.08 ;
```

### PR DESCRIPTION
**Pull request by fabiolrdiniz**
## Description
This is a PR proposing a fix for the `valid_range` attribute definition being written by GNSSRO converters.

P.S.: this PR is also addressing the comments from @jamiebresch after #766 has been merged into develop (see https://github.com/JCSDA-internal/ioda-converters/pull/766#discussion_r798867742 and https://github.com/JCSDA-internal/ioda-converters/pull/766#discussion_r798868919).

### Issue(s) addressed
- fixes #779

## Acceptance Criteria (Definition of Done)
Redefines the `valid_range` attribute.

## Dependencies
None

## Impact
None

### CODE REVIEW

**Comment by jamiebresch** [comment]
There could warnings for line 363 and line 392 `Warning: Missing '&' in continued character constant at (1) [-Wampersand]`.
Either add `&` before `e.g.`, or break the previous lines in the beginning of the whole string.

File: src/gnssro/gnssro_bufr2ioda.f90 [hunk 1]
```diff
@@ -301,7 +301,7 @@ program gnssro_bufr2ioda2
        gnssro_data%msl_alt(ndata)  = height
        gnssro_data%bend_ang(ndata)     = bend
        gnssro_data%bndoe_gsi(ndata)    = bend_error
-       gnssro_data%impact_para(ndata)  = impact! 
+       gnssro_data%impact_para(ndata)  = impact!
```
Comment (jamiebresch) [inline src/gnssro/gnssro_bufr2ioda.f90:304]: remove `!` as well?

**Comment by jamiebresch** [comment]
src/ncar-bufr2nc-fortran/gnssro_mod.f90 is out-of-sync with gnssro_bufr2ioda.f90. A few more changes are needed to bring it up-to-date. Is there a need to maintain src/ncar-bufr2nc-fortran?

**Comment by hailingz** [comment]
Thank you very much Fabio for addressing those issues!
do you know why the ctest failed?

File: src/gnssro/gnssro_bufr2ioda.f90 (hunk 1 above)
Comment (fabiolrdiniz) [reply src/gnssro/gnssro_bufr2ioda.f90:304]: Sure! The space has been removed automatically by my text editor. I just removed it by hand.

File: src/gnssro/gnssro_bufr2ioda.f90 [hunk 2]
```diff
@@ -381,7 +381,9 @@ program gnssro_bufr2ioda2
 
 call check( nf90_def_var(grpid_metadata, "ascending_flag",  NF90_INT, nlocs_dimid, varid_asce))
 call check( nf90_put_att(grpid_metadata, varid_asce, "longname", "the original occultation ascending/descending flag" ))
-call check( nf90_put_att(grpid_metadata, varid_asce, "valid_range", "0/descending or 1/ascending" ))
+call check( nf90_put_att(grpid_metadata, varid_asce, "valid_range", int((/ 0, 1 /))) )
+call check( nf90_put_att(grpid_metadata, varid_asce, "flag_values", int((/ 0, 1 /))) )
+call check( nf90_put_att(grpid_metadata, varid_asce, "flag_meanings", "descending ascending") )
```
Comment (hailingz) [inline src/gnssro/gnssro_bufr2ioda.f90:386]: This is very nice!

Comment (fabiolrdiniz) [reply src/gnssro/gnssro_bufr2ioda.f90:386]: > src/ncar-bufr2nc-fortran/gnssro_mod.f90 is out-of-sync with gnssro_bufr2ioda.f90. A few more changes are needed to bring it up-to-date. Is there a need to maintain src/ncar-bufr2nc-fortran?

Thanks again, @jamiebresch. I just fixed the other warning for `qfro` there. I'll leave the question about the maintenance of `src/ncar-bufr2nc-fortran` for the others because I'm not the right person to say about it.

**Comment by fabiolrdiniz** [comment]
> Thank you very much Fabio for addressing those issues! do you know why the ctest failed?

Yes, I know. I forgot to update the reference files after adding the flag values & meanings. Sorry reviewers! It should pass the CI tests.

**Comment by fabiolrdiniz** [comment]
> src/ncar-bufr2nc-fortran/gnssro_mod.f90 is out-of-sync with gnssro_bufr2ioda.f90. A few more changes are needed to bring it up-to-date. Is there a need to maintain src/ncar-bufr2nc-fortran?

Thanks again, @jamiebresch. I just fixed the other warning for `qfro` there. I'll leave the question about the maintenance of `src/ncar-bufr2nc-fortran` for the others because I'm not the right person to say about it.

**Comment by jamiebresch** [comment]
Since you are touching src/ncar-bufr2nc-fortran/gnssro_mod.f90, you can grab an updated version from https://github.com/jamiebresch/obs2ioda/blob/main/obs2ioda-v1/src/gnssro_mod.f90 if you want, but you will need to redo your valid_range changes.
I would propose to remove src/ncar-bufr2nc-fortran/gnssro_mod.f90 if it is not used.

**Comment by fabiolrdiniz** [comment]
@jamiebresch, I just pushed a version of the code following your suggestions for updating `src/ncar-bufr2nc-fortran/gnssro_mod.f90` and fixing the ampersand issue above.

**Review by hailingz — APPROVED** [review]
The GNSS RO converters look good to me!

**Comment by jamiebresch** [comment]
Thanks @fabiolrdiniz for addressing my concerns and being so thorough.

**Review by srherbener — APPROVED** [review]
It looks like the `ncar-bufr2nc-fortran/gnssro_mod.f90` is still outputting ioda v1 format. I think dealing with upgrading this converter to ioda v2 can be done in a subsequent PR. Ie, keep this PR focused on the fixes for the valid_range attribute.

What do others think?

**Comment by srherbener** [comment]
@jamiebresch are you okay with merging, or do you still have some comments you want addressed? Thanks!

**Comment by jamiebresch** [comment]
The fixes look good to me.
